ALTER TABLE users ADD COLUMN IF NOT EXISTS status VARCHAR DEFAULT 'pending';
ALTER TABLE users ADD COLUMN IF NOT EXISTS location_lat FLOAT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS location_lng FLOAT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS rating FLOAT DEFAULT 5.0;
ALTER TABLE users ADD COLUMN IF NOT EXISTS completed_deliveries INTEGER DEFAULT 0;
ALTER TABLE users ADD COLUMN IF NOT EXISTS volunteer_status VARCHAR DEFAULT 'pending';
ALTER TABLE users ADD COLUMN IF NOT EXISTS ngo_id UUID REFERENCES users(id);

ALTER TABLE donations ADD COLUMN IF NOT EXISTS volunteer_id UUID REFERENCES users(id);
ALTER TABLE donations ADD COLUMN IF NOT EXISTS delivery_status VARCHAR DEFAULT 'pending';
ALTER TABLE donations ADD COLUMN IF NOT EXISTS otp_code VARCHAR;
ALTER TABLE donations ADD COLUMN IF NOT EXISTS otp_verified BOOLEAN DEFAULT FALSE;
ALTER TABLE donations ADD COLUMN IF NOT EXISTS pickup_time TIMESTAMP;
ALTER TABLE donations ADD COLUMN IF NOT EXISTS delivery_time TIMESTAMP;
ALTER TABLE donations ADD COLUMN IF NOT EXISTS ai_confidence_score FLOAT;
